import type { Metadata } from "next";
import localFont from "next/font/local";
import SmoothScrolling from "@/components/SmoothScrolling";
import "./globals.css";

const raleway = localFont({
  src: [
    {
      path: "../public/fonts/raleway.woff2",
    },
  ],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Borth Community Mans Shed",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${raleway.variable} font-sans bg-white`}>
      <body className={`${raleway.variable} font-sans`}>
        <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>
  );
}
